export { Header } from './Header'
export { Hero } from './Hero'
export { About } from './About'
export { Services } from './Services'
export { Testimonials } from './Testimonials'
export { CTA } from './CTA'
export { Footer } from './Footer'
export { AnimatedSection, StaggerContainer } from './AnimatedSection'
